### ISSUE TITLE
argus_detection  | ModuleNotFoundError: No module named 'joblib'

### ISSUE THREAD

**Issue by fabpiaf** [RoblabWh/argus#9]
It seems the `argus_detection` is missing a needed python lib?
```
...
 Container argus_broker  Created
 Container argus_db  Created
 Container argus_vslam  Created
 Container argus_nodeodm  Created
 Container argus_detection  Created
 Container argus_worker  Created
 Container argus_webodm  Created
 Container argus  Created
Attaching to argus, argus_broker, argus_db, argus_detection, argus_nodeodm, argus_vslam, argus_webodm, argus_worker
argus_db         | 
argus_db         | PostgreSQL Database directory appears to contain a database; Skipping initialization
argus_db         | 
argus_db         | LOG:  database system was interrupted; last known up at 2024-11-25 16:04:24 UTC
argus_db         | LOG:  database system was not properly shut down; automatic recovery in progress
argus_db         | LOG:  redo starts at 0/217B698
argus_db         | LOG:  invalid record length at 0/2189BB8
argus_db         | LOG:  redo done at 0/2189B90
argus_db         | LOG:  last completed transaction was at log time 2024-11-25 16:04:59.990981+00
argus_db         | LOG:  MultiXact member wraparound protections are now enabled
argus_db         | LOG:  database system is ready to accept connections
argus_db         | LOG:  autovacuum launcher started
argus_broker     | 1:C 25 Nov 2024 16:05:38.526 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
argus_broker     | 1:C 25 Nov 2024 16:05:38.526 # Redis version=7.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
argus_broker     | 1:C 25 Nov 2024 16:05:38.526 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
argus_broker     | 1:M 25 Nov 2024 16:05:38.526 * Increased maximum number of open files to 10032 (it was originally set to 1024).
argus_broker     | 1:M 25 Nov 2024 16:05:38.526 * monotonic clock: POSIX clock_gettime
argus_broker     | 1:M 25 Nov 2024 16:05:38.526 * Running mode=standalone, port=6379.
argus_broker     | 1:M 25 Nov 2024 16:05:38.526 # Server initialized
argus_broker     | 1:M 25 Nov 2024 16:05:38.527 * Ready to accept connections
argus_nodeodm    | 
argus_vslam      |  * Serving Flask app 'slam_server'
argus_vslam      |  * Debug mode: off
argus_vslam      | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
argus_vslam      |  * Running on all addresses (0.0.0.0)
argus_vslam      |  * Running on http://127.0.0.1:7000
argus_vslam      |  * Running on http://172.19.0.3:7000
argus_vslam      | Press CTRL+C to quit
argus_worker     | Postgres is up - executing command
argus_worker     | wait-for-it.sh: waiting for broker:6379 without a timeout
argus_worker     | wait-for-it.sh: broker:6379 is available after 0 seconds
argus_worker     | wait-for-it.sh: waiting for webodm:8000 without a timeout
argus_detection  | Traceback (most recent call last):
argus_detection  |   File "/detection/main.py", line 2, in <module>
argus_detection  |     from detection_server import DetectionServer
argus_detection  |   File "/detection/detection_server.py", line 4, in <module>
argus_detection  |     from detection_process import DetectionProcess
argus_detection  |   File "/detection/detection_process.py", line 7, in <module>
argus_detection  |     from transformer_pipeline.inference.inference_engine import Inferencer
argus_detection  |   File "/detection/transformer_pipeline/inference/inference_engine.py", line 5, in <module>
argus_detection  |     from joblib.externals.cloudpickle import instance
argus_detection  | ModuleNotFoundError: No module named 'joblib'

```

**Comment by SchulteM42** [comment]
Yes, sorry. This was a small leftover from testing some new things. We removed the module.
